module.exports = [
  {
    name: "Driz'zt Do'Urden",
    backStory: "A dark elf ranger.",
    level: 10,
    exp: 0,
    gp: 300,
    abilities: [],
    item1: { name: "Scimitar", level: 3, type: "melee", damage: 6 },
    maxMana: 120,
    currentMana: 120,
    maxHealth: 120,
    currentHealth: 120,
    wisdom: 14,
    agility: 12,
    strength: 10,
    charisma: 12,
    img: "https://upload.wikimedia.org/wikipedia/en/c/cf/Drizzt.png",
  },
  {
    name: "Tasslehoff Burrfoot",
    backStory: "A kender thief.",
    level: 8,
    exp: 0,
    gp: 300,
    abilities: [],
    item1: { name: "Knife", level: 2, damage: 6, type: "melee" },
    item2: {},
    maxMana: 120,
    currentMana: 120,
    maxHealth: 120,
    currentHealth: 120,
    wisdom: 12,
    agility: 14,
    strength: 10,
    charisma: 12,
    img:
      "https://i.pinimg.com/originals/8d/cb/cf/8dcbcf45844c98edf62505f2dee22598.jpg",
  },
  {
    name: "Elric of Melnibone",
    backStory:
      "Prince of Melnibone, Servant of Arioch, Wielder of Stormbringer.",
    level: 15,
    exp: 0,
    gp: 300,
    abilities: [],
    item1: { name: "Scimitar", level: 4, damage: 6, type: "melee" },
    item2: {},
    maxMana: 120,
    currentMana: 120,
    maxHealth: 120,
    currentHealth: 120,
    wisdom: 17,
    agility: 14,
    strength: 10,
    charisma: 14,
    img:
      "https://i.pinimg.com/originals/37/35/c2/3735c202cf08e357e74a916f758fc962.jpg",
  },
  {
    name: "Raistlin",
    backStory: "Wizard of the black robes.",
    level: 15,
    exp: 0,
    gp: 2000,
    abilities: [],
    item1: { name: "Spellbook", level: 5, damage: 6, type: "sorcery" },
    item2: {},
    maxMana: 120,
    currentMana: 120,
    maxHealth: 120,
    currentHealth: 120,
    wisdom: 17,
    agility: 14,
    strength: 10,
    charisma: 14,
    img:
      "https://comicvine1.cbsistatic.com/uploads/scale_small/5/58395/1625964-200px_raistlin.png",
  },
  {
    name: "Noob",
    backStory: "a poor noob",
    level: 0,
    exp: 0,
    gp: 50,
    abilities: [],
    item1: { name: "pitchfork", level: 1, damage: 6, type: "melee" },
    item2: {},
    maxMana: 120,
    currentMana: 120,
    maxHealth: 120,
    currentHealth: 120,
    wisdom: 10,
    agility: 10,
    strength: 10,
    charisma: 10,
    img: "https://en.opisanie-kartin.com/images/2/image1472.jpg",
  },
];
