module.exports = [
  {
    name: "Driz'zt Do'Urden",
    backStory: "A dark elf ranger.",
    level: 10,
    exp: 0,
    gp: 300,
    abilities: [],
    item1: { name: "Scimitar", level: 3 },
    item2: { name: "Scimitar", level: 3 },
    mana: 12,
    health: 12,
    wisdom: 14,
    agility: 12,
    strength: 10,
    charisma: 12,
    sign: "Spider",
    img:
      "https://www.geekgirlauthority.com/wp-content/uploads/2018/09/drizzt-1080982-1280x0-1280x640.jpeg",
  },
  {
    name: "Tasslehoff Burrfoot",
    backStory: "A kender thief.",
    level: 8,
    exp: 0,
    gp: 300,
    abilities: [],
    item1: { name: "Knife", level: 2 },
    item2: {},
    mana: 12,
    health: 12,
    wisdom: 12,
    agility: 14,
    strength: 10,
    charisma: 12,
    sign: "Dragon",
    img:
      "https://i.pinimg.com/originals/8d/cb/cf/8dcbcf45844c98edf62505f2dee22598.jpg",
  },
  {
    name: "Elric of Melnibone",
    backStory:
      "Prince of Melnibone, Servant of Arioch, Wielder of Stormbringer.",
    level: 15,
    exp: 0,
    gp: 300,
    abilities: [],
    item1: { name: "Scimitar", level: 4 },
    item2: {},
    mana: 12,
    health: 12,
    wisdom: 17,
    agility: 14,
    strength: 10,
    charisma: 14,
    sign: "Dragon",
    img:
      "https://www.geekgirlauthority.com/wp-content/uploads/2018/09/drizzt-1080982-1280x0-1280x640.jpeg",
  },
  {
    name: "Raistlin",
    backStory: "Wizard of the black robes.",
    level: 15,
    exp: 0,
    gp: 2000,
    abilities: [],
    item1: { name: "Spellbook", level: 5 },
    item2: {},
    mana: 12,
    health: 12,
    wisdom: 17,
    agility: 14,
    strength: 10,
    charisma: 14,
    sign: "Elemental",
    img:
      "https://comicvine1.cbsistatic.com/uploads/scale_small/5/58395/1625964-200px_raistlin.png",
  },
  {
    name: "Noob",
    backStory: "a poor noob",
    level: 0,
    exp: 0,
    gp: 50,
    abilities: [],
    item1: { name: "pitchfork", level: 0 },
    item2: {},
    mana: 10,
    health: 10,
    wisdom: 10,
    agility: 10,
    strength: 10,
    charisma: 10,
    sign: "None",
    img: "https://en.opisanie-kartin.com/images/2/image1472.jpg",
  },
];
